### ISSUE TITLE
yii2-pdf  version???

### ISSUE THREAD

**Issue by huaiguoguo** [Borales/yii-pdf#13]
yii2-pdf  version???

**Comment by Borales** [comment]
@huaiguoguo what about it?

**Comment by huaiguoguo** [comment]
@Borales do you have a yii2-pdf version ?
you yii-pdf   is very niubility ！！

**Comment by Borales** [comment]
@huaiguoguo no, there are a lot of similar packages from other developers, 

I would recommend using this one - https://github.com/yii2tech/html2pdf
