### ISSUE TITLE
Composer - Requirements broken?

### ISSUE THREAD

**Issue by timrosede** [Borales/yii-pdf#5]
i Think, the Composer Requirements are broken?

Problem 1
    - Installation request for borales/yii-pdf dev-master -> satisfiable by borales/yii-pdf[dev-master].
    - borales/yii-pdf dev-master requires mpdf/mpdf dev-master -> no matching package found.

**Comment by vitalykhy** [comment]
The problem is actual now.
```
Problem 1
    - Installation request for borales/yii-pdf ^0.4.0 -> satisfiable by borales/yii-pdf[0.4.0].
    - borales/yii-pdf 0.4.0 requires mpdf/mpdf dev-master -> no matching package found.
```
